
package info.semanticsoftware.semassist.server;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SemanticServiceBrokerService", targetNamespace = "http://server.semassist.semanticsoftware.info/", wsdlLocation = "http://assistant.cs.concordia.ca:8879/SemAssist?wsdl")
public class SemanticServiceBrokerService
    extends Service
{

    private final static URL SEMANTICSERVICEBROKERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(info.semanticsoftware.semassist.server.SemanticServiceBrokerService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = info.semanticsoftware.semassist.server.SemanticServiceBrokerService.class.getResource(".");
            url = new URL(baseUrl, "http://assistant.cs.concordia.ca:8879/SemAssist?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://assistant.cs.concordia.ca:8879/SemAssist?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SEMANTICSERVICEBROKERSERVICE_WSDL_LOCATION = url;
    }

    public SemanticServiceBrokerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SemanticServiceBrokerService() {
        super(SEMANTICSERVICEBROKERSERVICE_WSDL_LOCATION, new QName("http://server.semassist.semanticsoftware.info/", "SemanticServiceBrokerService"));
    }

    /**
     * 
     * @return
     *     returns SemanticServiceBroker
     */
    @WebEndpoint(name = "SemanticServiceBrokerPort")
    public SemanticServiceBroker getSemanticServiceBrokerPort() {
        return super.getPort(new QName("http://server.semassist.semanticsoftware.info/", "SemanticServiceBrokerPort"), SemanticServiceBroker.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SemanticServiceBroker
     */
    @WebEndpoint(name = "SemanticServiceBrokerPort")
    public SemanticServiceBroker getSemanticServiceBrokerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.semassist.semanticsoftware.info/", "SemanticServiceBrokerPort"), SemanticServiceBroker.class, features);
    }

}
